(function () {
  // Simple localStorage-backed repository for Milestone 2 prototype
  const KEY_LISTS = 'ot_lists_v1';
  const KEY_HISTORY = 'ot_history_v1';

  function normalizeNameKey(value) {
    return String(value || '')
      .trim()
      .toLocaleLowerCase();
  }

  function buildUniqueName(baseName, existingNames) {
    const seed = String(baseName || '').trim() || 'Session';
    const taken = new Set(
      (Array.isArray(existingNames) ? existingNames : [])
        .map((name) => normalizeNameKey(name))
        .filter(Boolean)
    );

    if (!taken.has(normalizeNameKey(seed))) return seed;

    let n = 1;
    while (taken.has(normalizeNameKey(`${seed} ${n}`))) {
      n += 1;
    }
    return `${seed} ${n}`;
  }

  function loadBuiltins() {
    return fetch('data/builtins.json')
      .then((r) => r.json())
      .then((j) => j.lists || []);
  }

  function loadLists() {
    const raw = localStorage.getItem(KEY_LISTS);
    const custom = raw ? JSON.parse(raw) : [];
    return loadBuiltins().then((b) => {
      // merge builtins first, then custom after
      const all = b.concat(custom);
      return all;
    });
  }

  function saveList(list) {
    const raw = localStorage.getItem(KEY_LISTS);
    const custom = raw ? JSON.parse(raw) : [];
    const toSave = {
      ...list,
      updatedAt: Date.now(),
    };
    // if list is builtIn, push as a new custom copy (caller should have duplicated)
    const idx = custom.findIndex((l) => l.id === toSave.id);
    if (idx >= 0) custom[idx] = toSave;
    else custom.push(toSave);
    localStorage.setItem(KEY_LISTS, JSON.stringify(custom));
    return Promise.resolve();
  }

  function deleteList(listId) {
    const raw = localStorage.getItem(KEY_LISTS);
    const custom = raw ? JSON.parse(raw) : [];
    const filtered = custom.filter((l) => l.id !== listId);
    localStorage.setItem(KEY_LISTS, JSON.stringify(filtered));
    return Promise.resolve();
  }

  function duplicateList(list) {
    const copy = JSON.parse(JSON.stringify(list));
    copy.id = 'custom-' + Date.now();
    copy.builtIn = false;
    return saveList(copy).then(() => copy);
  }

  function loadHistory() {
    const raw = localStorage.getItem(KEY_HISTORY);
    const history = raw ? JSON.parse(raw) : [];
    return Promise.resolve(Array.isArray(history) ? history : []);
  }

  function saveHistorySession(sessionEntry) {
    const raw = localStorage.getItem(KEY_HISTORY);
    const history = raw ? JSON.parse(raw) : [];
    const safeHistory = Array.isArray(history) ? history : [];
    const incomingId = String(sessionEntry?.id || '').trim();
    const existingIndex = incomingId
      ? safeHistory.findIndex((entry) => String(entry?.id || '') === incomingId)
      : -1;
    const comparisonPool =
      existingIndex >= 0
        ? safeHistory.filter((_, idx) => idx !== existingIndex)
        : safeHistory;
    const existingNames = comparisonPool.map((entry) => entry?.listName || '');

    const incomingName =
      String(sessionEntry?.listName || '').trim() || 'Session';
    const resolvedName = sessionEntry?.autoGeneratedName
      ? buildUniqueName(incomingName, existingNames)
      : incomingName;

    const entry = {
      ...sessionEntry,
      listName: resolvedName,
      id: sessionEntry?.id || 'session-' + Date.now(),
      savedAt: Date.now(),
    };

    const next = safeHistory.slice();
    if (existingIndex >= 0) next[existingIndex] = entry;
    else next.push(entry);
    localStorage.setItem(KEY_HISTORY, JSON.stringify(next));
    return Promise.resolve(entry);
  }

  function renameHistorySession(sessionId, nextName) {
    const id = String(sessionId || '').trim();
    const name = String(nextName || '').trim();
    if (!id || !name) return Promise.resolve(null);

    const raw = localStorage.getItem(KEY_HISTORY);
    const history = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(history)) return Promise.resolve(null);

    const idx = history.findIndex((entry) => String(entry?.id || '') === id);
    if (idx < 0) return Promise.resolve(null);

    const nextKey = normalizeNameKey(name);
    const duplicate = history.some(
      (entry, index) =>
        index !== idx && normalizeNameKey(entry?.listName || '') === nextKey
    );
    if (duplicate) return Promise.resolve(null);

    const updated = {
      ...history[idx],
      listName: name,
      updatedAt: Date.now(),
    };
    const next = history.slice();
    next[idx] = updated;
    localStorage.setItem(KEY_HISTORY, JSON.stringify(next));
    return Promise.resolve(updated);
  }

  function deleteHistorySession(sessionId) {
    const id = String(sessionId || '').trim();
    if (!id) return Promise.resolve(false);

    const raw = localStorage.getItem(KEY_HISTORY);
    const history = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(history)) return Promise.resolve(false);

    const next = history.filter((entry) => String(entry?.id || '') !== id);
    if (next.length === history.length) return Promise.resolve(false);

    localStorage.setItem(KEY_HISTORY, JSON.stringify(next));
    return Promise.resolve(true);
  }

  window.repository = {
    loadLists,
    saveList,
    deleteList,
    duplicateList,
    loadHistory,
    saveHistorySession,
    renameHistorySession,
    deleteHistorySession,
  };
})();
